backend:
  type: es
  es:
    host: elasticsearch-master
    port: 9200
    logstash_prefix: "fluentbit"
    http_user: ""
    http_passwd: ""
    backend:
  type: loki
  loki:
    host: loki
    port: 3100
    labels:
      job: "fluent-bit"
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
