apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14-1
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluentd.conf
          subPath: fluentd.conf
      volumes:
      - name: config
        configMap:
          name: fluentd-config

