elasticsearchHosts: "http://elasticsearch-master:9200"
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"
readinessProbe:
  httpGet:
    path: /app/kibana
    port: 5601
  initialDelaySeconds: 60
  timeoutSeconds: 30
