apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
spec:
  ports:
    - port: 2020
      targetPort: 2020
      protocol: TCP
      name: http
  selector:
    app: fluent-bit