apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 24224
